### ISSUE TITLE
No package "jansson" error during build step

### ISSUE THREAD

**Issue by bistace** [rlorigro/GFAse#10]
Hello,

I wanted to try GFAse but I get an error during the make step on CentOS7 with gcc 9.2.0. Here is the relevant part of the log:
```
[ 15%] No patch step for 'project_bdsg'
config.status: creating config.mk
[ 15%] Performing configure step for 'project_bdsg'
config.status: creating htslib.pc.tmp
config.status: creating config.h
-- Checking for module 'jansson'
--   No package 'jansson' found
CMake Error at /env/products/cmake/3.19.1/share/cmake-3.19/Modules/FindPkgConfig.cmake:553 (message):
  A required package was not found
Call Stack (most recent call first):
  /env/products/cmake/3.19.1/share/cmake-3.19/Modules/FindPkgConfig.cmake:741 (_pkg_check_modules_internal)
  CMakeLists.txt:140 (pkg_check_modules)
```

Could you please help me solve this issue?

**Comment by rlorigro** [comment]
I noticed I've missed this in the Dependencies list on the Readme, so I will add it. Let me know if I missed anything else.

We also have a WDL and corresponding docker image here:
https://github.com/meredith705/gfase_wdl/tree/75fea4e1e7746c9d48f81d8e29ba425d7c75b6f9

which will run the appropriate alignments and feed them to GFAse automatically (I will also add this to the Readme)
