### ISSUE TITLE
Error while building, cannot find config.guess and config.sub

### ISSUE THREAD

**Issue by MartinSchmitz95** [rlorigro/GFAse#11]
Hello,
After installing all dependencies I get following error while building the project. 

`/GFAse/build/_deps/project_htslib-src
configure: error: cannot find required auxiliary files: config.guess config.sub
make[2]: *** [CMakeFiles/BUILD_HTS.dir/build.make:73: CMakeFiles/BUILD_HTS] Error 1
make[1]: *** [CMakeFiles/Makefile2:260: CMakeFiles/BUILD_HTS.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
`

**Comment by rlorigro** [comment]
Hi Martin,

Could you share some details about your operating system and version?

**Comment by MartinSchmitz95** [comment]
Hello Ryan,

thank you for your answer. My operating system is Ubuntu 20.04.2 LTS

cmake version 3.18.2
gcc version 9.4.0
zlib1g-dev, Version: 1:1.2.11.dfsg-2ubuntu1.5
libbz2-dev, Version: 1.0.8-2
libcurl4-openssl-dev, Version: 7.68.0-1ubuntu2.18
libjansson-dev, Version: 2.12-1build1

**Comment by MartinSchmitz95** [comment]
Sorry, I accidentally closed the issue.

**Comment by MartinSchmitz95** [comment]
Hi Ryan, the change resolves the issue. Thank you!
I still have some trouble building it but this issue is definitely solved with the change.

**Comment by rlorigro** [comment]
Ok well feel free to open another issue if you are unable to resolve your problem
