### ISSUE TITLE
How to generate kmer .fa file

### ISSUE THREAD

**Issue by scthree** [rlorigro/GFAse#20]
Dear Developers,

Thank you for this wonderful tool and your contributions to the community!

Forgive me if I'm asking a stupid question (I tried to google search an answer but did not find anything definitive). I would like to use GFAse to try to phase an assembly using parental kmers. I already have paternal/maternal kmer files generated with yak (.yak) and meryl (.meryl). How do I convert these files into fasta format for input into GFAse?

I know you're busy and appreciate your time--

Sincerely,
Steve

**Comment by rlorigro** [comment]
Hi Steve,

No worries, @meredith705 should be able to help with that

**Comment by meredith705** [comment]
Hello Steve, 

I have used [KMC3](https://github.com/refresh-bio/KMC) to generate these `kmer.fasta` files. KMC3 has a straightforward set of tools to make kmers and isolate unique kmers from each parent. 

The commands we use to get these kmers per parent are in the [kmc.wdl](https://github.com/meredith705/gfase_wdl/blob/51d86a0cadddf73a7689ecf44a24aa7825ea9729/tasks/kmc.wdl#L71). We then use the `kmc_tools dump` method and an `awk` command to create parental fasta files. [Here](https://github.com/meredith705/gfase_wdl/blob/main/workflows/gfase_tasks/gfase_trio_phase.wdl) is a `gfase_trio_phase.wdl` that takes in a gfa and parental fastq/fasta read files then makes the kmer.fasta files and runs gfase.  If you can run a WDL this script automates the pipeline for you. 

There might be a way to turn your meryl database kmers into a fasta file ( with the [print](https://meryl.readthedocs.io/en/latest/reference.html#databases:~:text=print%20is%20optional.%20If%20present%2C%20the%20k%2Dmers%20will%20be%20written%20to%20ASCII%20file(s)%20in%20the%20format%20%3Ck%2Dmer%3E%3Ctab%3E%3Cvalue%3E%3Ctab%3E%3Clabel%3E) or display command ) and then some version of text wrangling to turn the output into a fasta format for `gfase`. However, I have not tried this. 

Thanks for using our tool,
Melissa M

**Comment by scthree** [comment]
Thank you @rlorigro!

Hi Melissa, thank you greatly for your wonderful, detailed, and easy to understand explanation. I followed your instructions and was able to generate the kmers with KMC3.

I am having some difficulty installing GFAse (missing Jansson package) so re-opened an old thread...sorry for the additional trouble!

Sincerely,
Steve
