### ISSUE TITLE
terminate called after throwing an instance of 'std::out_of_range'

### ISSUE THREAD

**Issue by csuzhang** [rlorigro/GFAse#23]
Hi:
    I'm running GFAse on Shasta assembly. The program is terminated when unzipping chains. Here is the log:
                `Final unmerged score: 1.52998e+06`
                `[0h 39m 24s] Writing phasing results to file...`
                `[0h 39m 24s] Chaining homologous sequences...`
                `[0h 39m 26s] Writing GFA...`
                `[0h 39m 33s] Unzipping chains...`
                `terminate called after throwing an instance of 'std::out_of_range'`
                `  what():  at: key not present`
                `Command terminated by signal 6`

**Comment by jeizenga** [comment]
Are you able to share the data that led to the crash?

**Comment by csuzhang** [comment]
The Hi-C data are [Hi-C 1](https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG002/hpp_HG002_NA24385_son_v1/hic/downsampled/HG002.HiC_2_NovaSeq_rep1_run2_S1_L001_R1_001.fastq.gz) and [Hi-C 2](https://s3-us-west-2.amazonaws.com/human-pangenomics/NHGRI_UCSC_panel/HG002/hpp_HG002_NA24385_son_v1/hic/downsampled/HG002.HiC_2_NovaSeq_rep1_run2_S1_L001_R2_001.fastq.gz). The Shasta assembly is uploaded to Google Drive [Shasta assembly](https://drive.google.com/file/d/1sodGM3HlyPRhkIQcnjF-KaiYy7JrzWvA/view?usp=drive_link).

**Comment by rlorigro** [comment]
Hi @csuzhang, we are hoping to get to this soon. In the mean time, could you also try invoking `--use_simple_chainer` and see if the error persists?

**Comment by rlorigro** [comment]
Hi @csuzhang could you also share the command that you ran?

**Comment by csuzhang** [comment]
`bwa index Assembly-Phased.fasta`
`bwa mem -t 48 -5 -SP Assembly-Phased.fasta HG002.HiC_2_NovaSeq_rep1_run2_S1_L001_R1_001.fastq.gz HG002.HiC_2_NovaSeq_rep1_run2_S1_L001_R1_001.fastq.gz | samtools sort -n -@ 47 - -o hic_to_assembly.sorted_by_read.bam`
`phase_contacts_with_monte_carlo -i hic_to_assembly.sorted_by_read.bam -g Assembly-Phased.gfa -o gfase --skip_unzip -m 1 -t 48`

**Comment by jeizenga** [comment]
Are these the exact commands you used? If so, I think the issue might have been the `bwa mem` command. For one, it looks like you used the `R1` reads twice instead of both `R1` and `R2`. It's still not good that we crash on this input, but the problem might resolve if you fix the input.

**Comment by rlorigro** [comment]
I think there must be a mismatch with the command that was run and the command posted above, because the stderr says ` [0h 39m 33s] Unzipping chains...` but in the executable that would not appear if `--skip_unzip` was invoked:

```
    if (not skip_unzip) {
        cerr << t << "Unzipping chains... " << '\n';

        unzip(graph, id_map, overlaps, false, false);
        write_gfa_to_file(graph, id_map, overlaps, unzipped_gfa_path);
    }
```

**Comment by jeizenga** [comment]
I have processed the data and unfortunately can't replicate this crash. However, I aligned with BWA command before you posted your command, which is slightly different. I will try to replicate it exactly to see if that accounts for the discrepancy. Alternatively, you could provide your BAM files directly. Can you also check which commit/release of GFAse you're using?

**Comment by jeizenga** [comment]
I was able to replicate the crash by using the exact read mapping command that you did, and it should now be resolved.

**Comment by zhangjuncsu** [comment]
I'm sorry it took so long to reply to you. I have tried the newest version. The output of phase_0 and phase_1 is about 18M, and unphased is about 5.6G. 
The command I used: `phase_contacts_with_monte_carlo -i hic_to_assembly.sorted_by_read.bam -g Assembly-Phased.gfa -o gfase -m 1 -t 48`

**Comment by csuzhang** [comment]
I'm sorry it took so long to reply to you. I have tried the newest version. The output of phase_0 and phase_1 is about 18M, and unphased is about 5.6G.
The command I used: `phase_contacts_with_monte_carlo -i hic_to_assembly.sorted_by_read.bam -g Assembly-Phased.gfa -o gfase -m 1 -t 48`

**Comment by csuzhang** [comment]
1. The command I ran to align the reads: `bwa mem -t 48 -5 -SP Assembly-Phased.fasta HG002.HiC_2_NovaSeq_rep1_run2_S1_L001_R1_001.fastq.gz HG002.HiC_2_NovaSeq_rep1_run2_S1_L001_R2_001.fastq.gz | samtools sort -n -@ 48 - -o hic_to_assembly.sorted_by_read.bam`
2. [chained.gfa](https://drive.google.com/file/d/1nIhx_bsZypDckFKfcF4El7OiVFhHTCtZ/view?usp=drive_link); [contacts.csv.gz](https://github.com/rlorigro/GFAse/files/14830175/contacts.csv.gz)
3. When reruning with `--use_simple_chainer `, the output of phase_0 and phase_1 is about 2.5G and unphased is about 370M.

**Comment by rlorigro** [comment]
Thank you @csuzhang this is very helpful, we will work on this. In the mean time hopefully the simple chainer will get you what you need

**Comment by rlorigro** [comment]
@csuzhang could you also please share the `phases.csv` that you obtained from your original problematic run? It may help us debug faster

**Comment by csuzhang** [comment]
@rlorigro the files uploaded before may be wrong, here is the correct files [contacts.csv.gz](https://github.com/rlorigro/GFAse/files/14833307/contacts.csv.gz), [phases.csv](https://github.com/rlorigro/GFAse/files/14833325/phases.csv), [chained.gfa](https://drive.google.com/file/d/1pQfpAuqLG5D9zH19fxX3p48Bp1VnHt6Z/view?usp=drive_link), [Assembly-Phased.gfa](https://drive.google.com/file/d/1GB5DXvD3tRM80_CM7wPzUsnJneNZYKxb/view?usp=drive_link).

**Comment by rlorigro** [comment]
Ok thanks

**Comment by jeizenga** [comment]
@csuzhang For the Google Drive links, would you mind giving access to either joeizeng@gmail.com or jeizenga@ucsc.edu?

**Comment by jeizenga** [comment]
I believe this bug should now be fixed in the main branch. Thanks for pointing this issue out!
