### ISSUE TITLE
questions about this figures? 

### ISSUE THREAD

**Issue by zhangyixing3** [rlorigro/GFAse#33]
Hi, dear sir. I am very interested in the figure below. I am curious about whether there are specific tools to obtain these figures conveniently and directly .
![image](https://github.com/user-attachments/assets/d6e61dcc-62a8-4fb5-9e66-2de3258feddd)

**Comment by rlorigro** [comment]
Hi @zhangyixing3,

yes you can make these using this script:

https://github.com/rlorigro/TaskManager/blob/master/run_locally.py

and then running this to plot the output:

https://github.com/rlorigro/TaskManager/blob/master/bin/plot_resource_usage.py

I would ignore the install instructions on the Readme, you just need to clone the main branch and then install the correct python libs.

**Comment by zhangyixing3** [comment]
cool!   Thanks for your help.
